name: laravel
recipe: laravel
config:
  webroot: public
services:
  node:
    type: node
tooling:
    npm:
      service: node
    node:
      service: node
    phpunit:
      service: appserver
      description: "Run PHP Unit tests: lando phpunit"
      cmd: /app/vendor/bin/phpunit
    php-cs-fixer:
      service: appserver
      desription: "Analyze code against the WordPress coding standards with PHP-cs-fixer"
      cmd:
      - "vendor/bin/php-cs-fixer"
